export interface Env { DB: D1Database; ASSETS: Fetcher; INGEST_TOKEN?: string; QUOTE_C_COOKIE?: string; SNAPSHOT_URL?: string; }
type SecurityType = 'stock' | 'etf'; type Period = '1M' | '6M' | '1Y';
const DEFAULT_SNAPSHOT_URL = 'https://extquote.ainvest.com/index_api/indicator/v2/snapshot';
const jsonHeaders = { 'content-type': 'application/json; charset=utf-8' };
const corsHeaders = { 'access-control-allow-origin': '*', 'access-control-allow-headers': 'content-type, authorization, x-idempotency-key, x-theme-upload-token', 'access-control-allow-methods': 'GET, POST, OPTIONS' };
export const PERFORMANCE_INDICATORS = [['hotevent_etf_month1_chg_ratio','0','etf','1M'],['hotevent_etf_month6_chg_ratio','1','etf','6M'],['hotevent_etf_year1_chg_ratio','2','etf','1Y'],['hotevent_stock_month1_chg_ratio','3','stock','1M'],['hotevent_stock_month6_chg_ratio','4','stock','6M'],['hotevent_stock_year1_chg_ratio','5','stock','1Y']] as const;
function response(body: BodyInit | null, init: ResponseInit = {}) { const headers = new Headers(init.headers); for (const [k,v] of Object.entries(corsHeaders)) headers.set(k,v); return new Response(body,{...init,headers}); }
function error(message: string,status=400){return response(JSON.stringify({error:message}),{status,headers:jsonHeaders});}
function unavailable(status=200){return response(JSON.stringify({unavailable:true,error:'Live market data unavailable'}),{status,headers:{...jsonHeaders,'cache-control':'no-store'}});}
function authOk(request: Request,env: Env){if(!env.INGEST_TOKEN)return false;const value=request.headers.get('authorization')||'';const alternate=request.headers.get('x-theme-upload-token')||'';return value===`Bearer ${env.INGEST_TOKEN}`||alternate===env.INGEST_TOKEN;}
async function sha256(text:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function idFromHash(hash:string){return `theme_${hash.slice(0,24)}`;} function isRecord(value:unknown):value is Record<string,any>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
export function buildPerformanceRequest(groupId:string){return {symbol:[{type:'group_id_self',value:[groupId.trim()]}],indicator:PERFORMANCE_INDICATORS.map(([id,req_unique_id])=>({id,req_unique_id})),page:{begin:0,count:1}};}
export function buildExposureRequest(symbols:string[]){return {symbol:[{type:'market_code',value:symbols}],indicator:[{id:'total_market_value',req_unique_id:'marketValue'}],page:{begin:0,count:symbols.length}};}
function rangePeriod(date?:string){if(!date)return'day_1';const time=Date.parse(`${date}T12:00:00Z`);return Number.isFinite(time)?`day_${Math.max(1,Math.ceil((Date.now()-time)/86400000))}`:'day_1';}
export function buildQuotesRequest(symbols:string[],date?:string){return {symbol:[{type:'market_code',value:symbols}],indicator:[{id:'55',req_unique_id:'name'},{id:'10',req_unique_id:'last',attr:{trade_class:'intraday'}},{id:'inr-price_change_ratio_pct-sum',req_unique_id:'changePercent',attr:{trade_class:'intraday',time_period:rangePeriod(date)}},{id:'total_market_value',req_unique_id:'marketCap'}],page:{begin:0,count:symbols.length}};}
async function ingest(request:Request,env:Env){if(!authOk(request,env))return error('Unauthorized',401);const raw=await request.text();if(!raw||raw.length>2000000)return error('Result must be non-empty and under 2 MB',413);let parsed:Record<string,any>;try{parsed=JSON.parse(raw);}catch{return error('Invalid JSON',422);}const hash=request.headers.get('x-content-sha256')||await sha256(raw);if(!/^[a-f0-9]{64}$/.test(hash)||hash!==await sha256(raw))return error('Invalid content hash',422);const id=idFromHash(hash);const existing=await env.DB.prepare('SELECT id FROM themes WHERE content_sha256 = ?').bind(hash).first<{id:string}>();if(existing)return response(JSON.stringify({id:existing.id,duplicate:true}),{headers:jsonHeaders});const now=new Date().toISOString();await env.DB.prepare('INSERT INTO themes (id,created_at,event_date,theme,source_url,cover_url,stock_count,etf_count,content_sha256,byte_length,raw_json) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(id,now,typeof parsed.date==='string'?parsed.date:null,typeof parsed.theme==='string'?parsed.theme:'Untitled theme',typeof parsed.url==='string'?parsed.url:null,typeof parsed.cover==='string'?parsed.cover:null,Array.isArray(parsed.ThemeStocks)?parsed.ThemeStocks.length:0,Array.isArray(parsed.ThemeEtfs)?parsed.ThemeEtfs.length:0,hash,new TextEncoder().encode(raw).byteLength,raw).run();return response(JSON.stringify({id,duplicate:false}),{status:201,headers:jsonHeaders});}
async function listThemes(request:Request,env:Env){const url=new URL(request.url);const q=(url.searchParams.get('q')||'').trim();const limit=Math.min(Math.max(Number(url.searchParams.get('limit')||50),1),100);const rows=q?await env.DB.prepare('SELECT id,created_at,event_date,theme,source_url,cover_url,stock_count,etf_count FROM themes WHERE theme LIKE ? ORDER BY created_at DESC LIMIT ?').bind(`%${q}%`,limit).all():await env.DB.prepare('SELECT id,created_at,event_date,theme,source_url,cover_url,stock_count,etf_count FROM themes ORDER BY created_at DESC LIMIT ?').bind(limit).all();return response(JSON.stringify({themes:rows.results||[]}),{headers:jsonHeaders});}
async function getRaw(id:string,env:Env){return env.DB.prepare('SELECT raw_json FROM themes WHERE id = ?').bind(id).first<{raw_json:string}>();} async function getTheme(id:string,env:Env){const row=await getRaw(id,env);if(!row)return error('Theme not found',404);return response(row.raw_json,{headers:{...jsonHeaders,'cache-control':'public, max-age=60'}});}
function selections(parsed:Record<string,any>,type:SecurityType){const key=type==='stock'?'ThemeStocks':'ThemeEtfs';const items=Array.isArray(parsed[key])?parsed[key]:[];return items.filter(isRecord).map(item=>({market_code:String(item.market_code||'').trim(),exposure:Number(item['Theme exposure']),rationale:item.theme_rationale})).filter(item=>item.market_code.includes(':'));}
function idx(indicators:any[],key:string){const byReq=indicators.findIndex(x=>x?.req_unique_id===key);return byReq>=0?byReq:indicators.findIndex(x=>x?.id===key);} function num(value:unknown){const n=Number(value);return value===null||value===undefined||value===''||!Number.isFinite(n)?null:n;} function symbol(code:string){return code.split(':').pop()||code;}
async function upstream(body:unknown,env:Env,language:string){if(!env.QUOTE_C_COOKIE)return null;const r=await fetch(env.SNAPSHOT_URL||DEFAULT_SNAPSHOT_URL,{method:'POST',headers:{'content-type':'application/json',accept:'application/json','accept-language':language,cookie:env.QUOTE_C_COOKIE,'x-auth-progid':'7080'},body:JSON.stringify(body)});if(!r.ok)return null;const data:any=await r.json();return data?.status_code===0?data:null;}
async function cached(request:Request,key:string,fn:()=>Promise<Response>){const cache=(caches as any).default;const cacheRequest=new Request(`${new URL(request.url).origin}/__live-cache/${key}`);const hit=await cache?.match(cacheRequest);if(hit)return hit;const out=await fn();if(out.ok)await cache?.put(cacheRequest,out.clone());return out;}
async function live(request:Request,env:Env,id:string){const row=await getRaw(id,env);if(!row)return error('Theme not found',404);const url=new URL(request.url);const type=url.searchParams.get('securityType') as SecurityType||'stock';const period=url.searchParams.get('period') as Period||'1M';if(!['stock','etf'].includes(type)||!['1M','6M','1Y'].includes(period))return error('Invalid live query',422);return cached(request,`${id}-live-${type}-${period}`,async()=>{const body=await upstream(buildPerformanceRequest(id),env,request.headers.get('accept-language')||'en');if(!body)return unavailable(502);const indicators=body.data?.indicator||[];const values=body.data?.data?.[0]?.value||[];const spec=PERFORMANCE_INDICATORS.find(x=>x[2]===type&&x[3]===period);const position=idx(indicators,spec?.[1]||'');const points=position>=0&&Array.isArray(values[position]?.v)?values[position].v.map((p:any)=>({date:new Date(Number(p?.t)).toISOString().slice(0,10),percentage:num(p?.p)})).filter((p:any)=>p.percentage!==null):[];return response(JSON.stringify({securityType:type,period,points}),{headers:{...jsonHeaders,'cache-control':'public, max-age=120'}});});}
async function marketData(request:Request,env:Env,id:string,type:SecurityType,kind:'quotes'|'exposure-map'){const row=await getRaw(id,env);if(!row)return error('Theme not found',404);if(!['stock','etf'].includes(type))return error('Invalid security type',422);let parsed:any;try{parsed=JSON.parse(row.raw_json);}catch{return unavailable(502);}const selected=selections(parsed,type),symbols=selected.map(x=>x.market_code);if(!symbols.length)return response(JSON.stringify(kind==='quotes'?{rows:[]}:{points:[]}),{headers:jsonHeaders});return cached(request,`${id}-${kind}-${type}`,async()=>{const body=await upstream(kind==='quotes'?buildQuotesRequest(symbols,parsed.date):buildExposureRequest(symbols),env,request.headers.get('accept-language')||'en');if(!body)return unavailable(502);const indicators=body.data?.indicator||[],rows=body.data?.data||[];if(kind==='exposure-map'){const marketIndex=idx(indicators,'marketValue');const points=selected.flatMap(s=>{const r=rows.find((x:any)=>x?.symbol_code===s.market_code),value=num(r?.value?.[marketIndex]?.v);return value&&value>0?[{symbol:symbol(s.market_code),marketCode:s.market_code,exposure:num(s.exposure),marketValue:value/1e9}]:[]});return response(JSON.stringify({points}),{headers:{...jsonHeaders,'cache-control':'public, max-age=120'}});}const indexes={name:idx(indicators,'name'),last:idx(indicators,'last'),changePercent:idx(indicators,'changePercent'),marketValue:idx(indicators,'marketCap')};const out=selected.map(s=>{const r=rows.find((x:any)=>x?.symbol_code===s.market_code);const value=(key:keyof typeof indexes)=>indexes[key]>=0?r?.value?.[indexes[key]]?.v:null;return {symbol:symbol(s.market_code),marketCode:s.market_code,name:value('name')==null?null:String(value('name')),last:num(value('last')),changePercent:num(value('changePercent')),marketValue:num(value('marketValue')),exposure:num(s.exposure),rationale:s.rationale??null};});return response(JSON.stringify({rows:out}),{headers:{...jsonHeaders,'cache-control':'public, max-age=120'}});});}
export default {async fetch(request:Request,env:Env):Promise<Response>{if(request.method==='OPTIONS')return response(null,{status:204});const url=new URL(request.url);try{if(url.pathname==='/api/themes'&&request.method==='POST')return ingest(request,env);if(url.pathname==='/api/themes'&&request.method==='GET')return listThemes(request,env);if(url.pathname.startsWith('/api/themes/')&&request.method==='GET'){const parts=url.pathname.slice('/api/themes/'.length).split('/'),id=parts[0];if(parts[1]==='live')return live(request,env,id);if(parts[1]==='quotes'||parts[1]==='exposure-map')return marketData(request,env,id,(url.searchParams.get('securityType')||'stock') as SecurityType,parts[1]);return getTheme(id,env);}return env.ASSETS.fetch(request);}catch(cause){console.error(cause instanceof Error?cause.message:'request failed');return error('Internal server error',500);}}};
